version: "3"

services:

  database:
    image: heuzon/bc_fastapi-database:v0.1
    ports:
      - 5432:5432
    container_name: psql_database   
    
  app_api:
    image: heuzon/bc_fastapi-app_api:v0.1
    depends_on:
    - database
    ports:
      - 8080:8080
    container_name: fastapi_app