version: "3"

services:

  database:
    image: heuzon/pg_test_base
    ports:
      - 5432:5432
    container_name: database

  app_api:
    build: .
    depends_on:
    - database
    ports:
      - 8080:8080

    